version: 2.1

parameters:
  project_dir:
    type: string
    default: "~/tennis-app"

orbs:
  node: circleci/node@4.5.1

jobs:
  checkout_and_test:
    docker:
      - image: cimg/php:8.1.13-browsers
      - image: cimg/mysql:8.0
        environment:
          MYSQL_DATABASE: tennis_app_db
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ROOT_HOST: "%"
    environment:
      - APP_ENV: testing
      - APP_DEBUG: true
      - DB_CONNECTION: mysql
      - DB_HOST: 127.0.0.1
      - DB_PORT: 3306
      - DB_USERNAME: root
      - DB_PASSWORD: root
      - DB_DATABASE: tennis_app_db
      - REDIS_HOST: 127.0.0.1
      - APP_KEY: base64:vohQOwQXtlhSKIT6me4ZKuf/dgwz0lajuM91DrGgrxI=
    working_directory: << pipeline.parameters.project_dir >>

    steps:
      - checkout:
          path: << pipeline.parameters.project_dir >>
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - restore_cache:
          keys:
            - v2-composer-{{ checksum "backend/composer.lock" }}
            - v2-composer-
      - restore_cache:
          keys:
            - v2-npm-{{ checksum "backend/package.json" }}
            - v2-npm-
      - run:
          name: build
          command: |
            cd ./backend
            pwd
            composer install
            npm install
            npm run build
            php artisan migrate
      - save_cache:
          key: v2-composer-{{ checksum "backend/composer.lock" }}
          paths:
            - << pipeline.parameters.project_dir >>/backend/vendor
      - save_cache:
          key: v2-npm-{{ checksum "backend/package.json" }}
          paths:
            - << pipeline.parameters.project_dir >>/backend/node_modules
      - run:
          name: Run phpunit
          command: |
            cd ./backend
            php ./vendor/bin/phpunit
      - persist_to_workspace:
          root: << pipeline.parameters.project_dir >>
          paths:
            - .

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - checkout_and_test:
          name: checkout_and_test